#!/usr/bin/env node
// Friendly interactive .env builder for server-Jacky.
// Run from the server-jacky/ directory: node setup-env.mjs
//
// Asks for 3 secrets, writes .env with everything wired up,
// then runs the 3 connection tests so you know it works.

import { promises as fs, createReadStream } from 'node:fs'
import readline from 'node:readline/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ENV_PATH = path.join(HERE, '.env')

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

async function ask(question) {
  process.stdout.write('\n')
  let val = ''
  while (!val.trim()) {
    val = (await rl.question(question)).trim()
    if (!val) console.log('⚠ empty — please paste the value and press Enter.')
  }
  return val
}

console.log('\n🎪 Server-Jacky setup\n')
console.log('I need 3 secrets. Open jacky-secrets.txt on your Desktop, copy one at a time, paste below.\n')

const anthropicKey = await ask('1️⃣  Paste your Anthropic API key (starts with sk-ant-...):\n> ')
if (!anthropicKey.startsWith('sk-ant-')) {
  console.log('⚠ Hmm — that doesn\'t start with sk-ant-. Continuing anyway, you can re-run if it\'s wrong.')
}

const adminPwd = await ask('2️⃣  Paste the admin@bigstarcircus.com.au Titan password:\n> ')

const supabaseKey = await ask('3️⃣  Paste your Supabase service_role key (long string starting with eyJ...):\n> ')
if (!supabaseKey.startsWith('eyJ')) {
  console.log('⚠ Hmm — that doesn\'t look like a JWT. Continuing anyway.')
}

rl.close()

const envContent = `# Server-Jacky env — generated by setup-env.mjs
# Never commit this file.

# Claude / Anthropic
ANTHROPIC_API_KEY=${anthropicKey}
JACKY_MODEL=claude-sonnet-4-5
JACKY_MAX_TOKENS=4096

# admin@bigstarcircus.com.au — Titan Email
ADMIN_IMAP_HOST=imap.titan.email
ADMIN_IMAP_PORT=993
ADMIN_IMAP_USER=admin@bigstarcircus.com.au
ADMIN_IMAP_PASSWORD=${adminPwd}
ADMIN_SMTP_HOST=smtp.titan.email
ADMIN_SMTP_PORT=465
ADMIN_SMTP_USER=admin@bigstarcircus.com.au
ADMIN_SMTP_PASSWORD=${adminPwd}
ADMIN_FROM_NAME=Jacky · Big Star Circus
ADMIN_FROM_EMAIL=admin@bigstarcircus.com.au

# Supabase
SUPABASE_URL=https://dbpbfcxhbaeyoyoyllfp.supabase.co
SUPABASE_SERVICE_ROLE_KEY=${supabaseKey}
SUPABASE_TENANT_SLUG=bigstarcircus

# Operating mode
JACKY_STAGE=1
JACKY_DRY_RUN=false
JACKY_TZ=Australia/Brisbane

# Logging
LOG_LEVEL=info
LOG_FILE=
`

await fs.writeFile(ENV_PATH, envContent, 'utf8')
console.log(`\n✅ Wrote ${ENV_PATH}`)
console.log('\n🎪 Ready to test! Run these one at a time:\n')
console.log('   npm run test:claude    # verifies Anthropic')
console.log('   npm run test:imap      # verifies admin@ IMAP login')
console.log('   npm run test:smtp      # verifies admin@ SMTP login')
console.log('\nIf all three say ✅, you\'re ready to deploy.\n')
