'use client'

// Training portal — hero, module list, quick-start checklist, submit ticket.
//
// VOICE: each module ships with a pre-rendered MP3 generated by msedge-tts
// using en-AU-NatashaNeural (premium Australian female neural voice). The
// audio file is the source of truth — same voice, every visit, every browser.
// No more SpeechSynthesis lottery where module 11 picks a male voice.
//
// VIDEO AVATAR: while audio plays, the Jacky portrait animates using the Web
// Audio API. An AnalyserNode reads the live frequency data; the value drives
// a halo pulse, mouth-area opening, and gentle head sway. CSS keyframes
// handle idle breathing and eye blinks. The result is a true "talking video"
// feel without external lip-sync tooling or paid services.

import { useEffect, useMemo, useRef, useState } from 'react'
import type { TrainingModule } from './modules'
import { submitSupportTicket } from './actions'

const PROGRESS_KEY = 'bsc-training-progress-v1'

type Progress = {
  completed: string[]
  startedAt: string | null
}

function loadProgress(): Progress {
  if (typeof window === 'undefined') return { completed: [], startedAt: null }
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    if (raw) return JSON.parse(raw) as Progress
  } catch { /* ignore */ }
  return { completed: [], startedAt: null }
}

function saveProgress(p: Progress) {
  try { localStorage.setItem(PROGRESS_KEY, JSON.stringify(p)) } catch { /* ignore */ }
}

export function TrainingPortal({
  modules,
  userName,
}: {
  modules: TrainingModule[]
  userName: string | null
}) {
  const [progress, setProgress] = useState<Progress>({ completed: [], startedAt: null })
  const [activeId, setActiveId] = useState<string | null>(null)
  const [mounted, setMounted] = useState(false)
  const [ticketOpen, setTicketOpen] = useState(false)

  useEffect(() => {
    setProgress(loadProgress())
    setMounted(true)
  }, [])

  useEffect(() => {
    if (mounted) saveProgress(progress)
  }, [progress, mounted])

  function toggleComplete(id: string) {
    setProgress((p) => {
      const set = new Set(p.completed)
      if (set.has(id)) set.delete(id)
      else set.add(id)
      return { ...p, completed: [...set], startedAt: p.startedAt ?? new Date().toISOString() }
    })
  }

  const completedCount = useMemo(() => progress.completed.length, [progress])
  const pct = Math.round((completedCount / modules.length) * 100)

  return (
    <div className="space-y-6">
      <AvatarKeyframes />

      {/* Hero banner */}
      <div className="rounded-3xl overflow-hidden shadow-xl border-4 border-[#D72027] bg-gradient-to-br from-zinc-900 via-zinc-800 to-zinc-900 relative">
        <div className="absolute inset-0 opacity-10" style={{
          backgroundImage: 'radial-gradient(circle at 20% 30%, #FFC107 0%, transparent 25%), radial-gradient(circle at 80% 70%, #D72027 0%, transparent 30%)',
        }} />
        <div className="relative p-8 sm:p-10 grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
          <div className="md:col-span-1 flex justify-center">
            <JackyVideoAvatar size={180} level={0} idle />
          </div>
          <div className="md:col-span-2 text-white">
            <div className="text-xs uppercase tracking-widest text-amber-300 font-extrabold mb-2">
              Welcome to the BSC CRM Support Portal
            </div>
            <h2 className="text-3xl sm:text-4xl font-extrabold leading-tight mb-3">
              Hey {userName ?? 'there'} 🎪 I&apos;m Jacky. Let me show you around.
            </h2>
            <p className="text-zinc-300 mb-4 leading-relaxed">
              Eleven short modules. Tap the play button on any card — I&apos;ll walk you through it in my own voice while my portrait talks along.
              Same warm Australian voice every time. Try It links drop you straight into the feature.
            </p>
            <div className="flex items-center gap-3 flex-wrap">
              <a
                href="#module-1"
                onClick={() => {
                  if (!progress.startedAt) setProgress((p) => ({ ...p, startedAt: new Date().toISOString() }))
                }}
                className="bg-gradient-to-r from-[#FFC107] to-amber-400 text-zinc-900 font-extrabold text-sm px-5 py-3 rounded-xl shadow-md hover:shadow-lg"
              >
                ▶ Start Training
              </a>
              <button
                onClick={() => setTicketOpen(true)}
                className="bg-zinc-800 border-2 border-zinc-700 text-white font-extrabold text-sm px-5 py-3 rounded-xl hover:bg-zinc-700"
              >
                🎫 Submit Ticket
              </button>
              <div className="ml-auto text-xs">
                <div className="text-amber-300 font-extrabold">{completedCount} / {modules.length} done · {pct}%</div>
                <div className="w-32 h-1.5 bg-white/20 rounded-full mt-1 overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-[#FFC107] to-amber-300 rounded-full transition-all" style={{ width: `${pct}%` }} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Start checklist */}
      <QuickStart progress={progress} modules={modules} onToggle={toggleComplete} />

      {/* Modules */}
      <div className="space-y-4">
        {modules.map((m) => (
          <ModuleCard
            key={m.id}
            module={m}
            done={progress.completed.includes(m.id)}
            active={activeId === m.id}
            onToggleDone={() => toggleComplete(m.id)}
            onSpeakStateChange={(speaking) => setActiveId(speaking ? m.id : null)}
          />
        ))}
      </div>

      {/* Footer support */}
      <div className="bg-white rounded-2xl shadow-sm border-2 border-zinc-200 p-6 text-center">
        <div className="text-4xl mb-2">🆘</div>
        <h3 className="text-lg font-extrabold text-zinc-900 mb-1">Still stuck?</h3>
        <p className="text-sm text-zinc-600 mb-4">
          Ask Jacky in chat, submit a ticket, or email Rhett at <a href="mailto:admin@bigstarcircus.com.au" className="font-bold text-[#D72027] hover:underline">admin@bigstarcircus.com.au</a>.
        </p>
        <div className="flex items-center justify-center gap-2 flex-wrap">
          <a href="/jacky" className="bg-gradient-to-r from-[#D72027] to-[#A0151B] text-white font-extrabold text-sm px-4 py-2.5 rounded-lg shadow-md hover:shadow-lg">
            🎪 Ask Jacky
          </a>
          <button onClick={() => setTicketOpen(true)} className="bg-zinc-900 text-white font-extrabold text-sm px-4 py-2.5 rounded-lg hover:bg-zinc-800">
            🎫 Submit Ticket
          </button>
        </div>
      </div>

      {ticketOpen && <TicketModal onClose={() => setTicketOpen(false)} userName={userName} />}
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────
// Jacky video avatar — animated portrait that "talks" when audio plays
// ────────────────────────────────────────────────────────────────────

// One set of @keyframes shared by every avatar instance — keeps the CSS
// payload small and avoids inline-style churn on every frame.
function AvatarKeyframes() {
  return (
    <style jsx global>{`
      @keyframes jacky-breathe {
        0%, 100% { transform: scale(1); }
        50%      { transform: scale(1.018); }
      }
      @keyframes jacky-sway {
        0%, 100% { transform: translateY(0) rotate(-0.4deg); }
        50%      { transform: translateY(-1px) rotate(0.4deg); }
      }
      @keyframes jacky-blink {
        0%, 92%, 100% { transform: scaleY(0); opacity: 0; }
        94%, 98%      { transform: scaleY(1); opacity: 0.55; }
      }
      @keyframes jacky-halo {
        0%, 100% { opacity: 0.45; transform: scale(1);    }
        50%      { opacity: 0.65; transform: scale(1.04); }
      }
      @keyframes jacky-mouth-talk {
        0%   { transform: scaleY(0.2) translateY(0);    }
        20%  { transform: scaleY(0.85) translateY(0.5px); }
        40%  { transform: scaleY(0.35) translateY(0);    }
        60%  { transform: scaleY(0.95) translateY(0.5px); }
        80%  { transform: scaleY(0.4)  translateY(0);    }
        100% { transform: scaleY(0.7)  translateY(0.5px); }
      }
    `}</style>
  )
}

// `level` is an audio amplitude in [0, 1] driven by AnalyserNode. When 0 +
// `idle` is true the avatar still breathes and blinks — when level > 0 the
// portrait sways, the halo pulses, and the mouth-area animates.
function JackyVideoAvatar({
  size = 120,
  level,
  idle = false,
  ringless = false,
}: {
  size?: number
  level: number
  idle?: boolean
  ringless?: boolean
}) {
  // Clamp + soften so a low whisper still moves the halo a bit.
  const l = Math.max(0, Math.min(1, level))
  const speaking = l > 0.04
  const halo = ringless
    ? null
    : (
      <div
        className="absolute inset-0 rounded-full bg-gradient-to-br from-[#D72027] to-amber-400 blur-2xl pointer-events-none"
        style={{
          opacity: 0.35 + l * 0.45,
          transform: `scale(${1 + l * 0.18})`,
          transition: 'opacity 80ms linear, transform 80ms linear',
          animation: !speaking ? 'jacky-halo 3.6s ease-in-out infinite' : undefined,
        }}
      />
    )

  return (
    <div className="relative" style={{ width: size, height: size }}>
      {halo}
      {/* Portrait wrapper — gets breath idle anim or speech sway when active */}
      <div
        className="relative w-full h-full"
        style={{
          animation: speaking
            ? 'jacky-sway 0.9s ease-in-out infinite'
            : (idle ? 'jacky-breathe 4.2s ease-in-out infinite' : undefined),
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/jacky-avatar.png"
          alt="Jacky — your BSC AI admin"
          width={size}
          height={size}
          className={`relative rounded-full object-cover border-4 border-white shadow-2xl ${ringless ? '' : 'ring-4 ring-amber-300/40'}`}
          style={{ width: size, height: size }}
        />

        {/* Mouth-area animation overlay. Positioned over the lower-third of
            the face. When speaking, scaleY oscillates so the lower face
            "moves" — not true lip-sync but reads as a talking video. */}
        {speaking && (
          <span
            aria-hidden
            className="absolute rounded-full bg-zinc-900/35 mix-blend-multiply"
            style={{
              left:   `${size * 0.36}px`,
              top:    `${size * 0.66}px`,
              width:  `${size * 0.28}px`,
              height: `${size * 0.075}px`,
              transformOrigin: 'center top',
              animation: 'jacky-mouth-talk 360ms ease-in-out infinite',
            }}
          />
        )}

        {/* Eye blink overlay — two thin horizontal lids that flick down every
            ~3.5s. The strip rides over both eyes simultaneously. */}
        <span
          aria-hidden
          className="absolute rounded bg-zinc-800/0"
          style={{
            left:   `${size * 0.24}px`,
            top:    `${size * 0.41}px`,
            width:  `${size * 0.52}px`,
            height: `${size * 0.06}px`,
            background: 'rgba(60, 38, 30, 0.85)',
            transformOrigin: 'center top',
            animation: `jacky-blink ${speaking ? 2.4 : 3.6}s ease-in-out infinite`,
          }}
        />
      </div>

      {/* "Speaking" badge — a soft amber pip under the avatar when audio is
          active. Communicates state without being noisy. */}
      {speaking && (
        <div
          className="absolute -bottom-1 left-1/2 -translate-x-1/2 bg-amber-400 text-zinc-900 text-[9px] font-extrabold uppercase tracking-widest px-1.5 py-0.5 rounded-full shadow"
          style={{ opacity: 0.85 + l * 0.15 }}
        >
          ● Talking
        </div>
      )}
    </div>
  )
}

// ────────────────────────────────────────────────────────────────────
// Quick Start checklist
// ────────────────────────────────────────────────────────────────────

function QuickStart({
  progress,
  modules,
  onToggle,
}: {
  progress: Progress
  modules: TrainingModule[]
  onToggle: (id: string) => void
}) {
  const items = modules.slice(0, 6) // first 6 = quick start essentials
  return (
    <section className="bg-white rounded-2xl shadow-sm border-2 border-zinc-200 p-5">
      <div className="flex items-baseline justify-between mb-3">
        <h3 className="text-lg font-extrabold text-zinc-900">Quick Start checklist</h3>
        <span className="text-xs text-zinc-500">
          {items.filter((m) => progress.completed.includes(m.id)).length} / {items.length}
        </span>
      </div>
      <ul className="space-y-1.5">
        {items.map((m) => {
          const done = progress.completed.includes(m.id)
          return (
            <li key={m.id}>
              <button
                onClick={() => onToggle(m.id)}
                className="w-full flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-zinc-50 text-left"
              >
                <span className={`w-5 h-5 rounded border-2 shrink-0 flex items-center justify-center ${done ? 'bg-emerald-500 border-emerald-600 text-white' : 'border-zinc-300'}`}>
                  {done && '✓'}
                </span>
                <span className={`flex-1 text-sm ${done ? 'line-through text-zinc-400' : 'text-zinc-800 font-bold'}`}>
                  {m.emoji} Module {m.number} — {m.title}
                </span>
                <a
                  href={`#module-${m.number}`}
                  onClick={(e) => e.stopPropagation()}
                  className="text-[10px] font-extrabold text-[#D72027] hover:underline shrink-0"
                >
                  Jump →
                </a>
              </button>
            </li>
          )
        })}
      </ul>
    </section>
  )
}

// ────────────────────────────────────────────────────────────────────
// Module card with pre-rendered audio + audio-driven avatar
// ────────────────────────────────────────────────────────────────────

function ModuleCard({
  module,
  done,
  onToggleDone,
  onSpeakStateChange,
}: {
  module: TrainingModule
  done: boolean
  active: boolean
  onToggleDone: () => void
  onSpeakStateChange: (speaking: boolean) => void
}) {
  const [playing, setPlaying] = useState(false)
  const [level, setLevel] = useState(0) // 0..1 — drives avatar animation
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const ctxRef = useRef<AudioContext | null>(null)
  const analyserRef = useRef<AnalyserNode | null>(null)
  const dataRef = useRef<Uint8Array | null>(null)
  const rafRef = useRef<number | null>(null)

  useEffect(() => {
    return () => {
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current)
      try { audioRef.current?.pause() } catch {}
      try { ctxRef.current?.close() } catch {}
    }
  }, [])

  function tickAnalyser() {
    const an = analyserRef.current
    const buf = dataRef.current
    if (!an || !buf) return
    // The TS lib types the param as Uint8Array<ArrayBuffer>; our ref is the
    // same shape, but TS sometimes infers the looser ArrayBufferLike. Cast
    // here to keep both sides happy without altering runtime behaviour.
    an.getByteTimeDomainData(buf as unknown as Uint8Array<ArrayBuffer>)
    // RMS over time-domain samples — 128 is silence, deviation = volume.
    let sum = 0
    for (let i = 0; i < buf.length; i++) {
      const v = (buf[i] - 128) / 128
      sum += v * v
    }
    const rms = Math.sqrt(sum / buf.length) // 0..~0.6 in practice
    // Boost the dynamic range so even soft voice produces visible motion.
    const next = Math.min(1, rms * 3.2)
    setLevel(next)
    rafRef.current = requestAnimationFrame(tickAnalyser)
  }

  function ensureGraph() {
    if (ctxRef.current && analyserRef.current && audioRef.current) return
    if (!audioRef.current) return
    type WebkitWindow = Window & typeof globalThis & { webkitAudioContext?: typeof AudioContext }
    const W = window as WebkitWindow
    const Ctor = W.AudioContext ?? W.webkitAudioContext
    if (!Ctor) return
    const ctx = new Ctor()
    const src = ctx.createMediaElementSource(audioRef.current)
    const an = ctx.createAnalyser()
    an.fftSize = 256
    src.connect(an)
    an.connect(ctx.destination)
    ctxRef.current = ctx
    analyserRef.current = an
    dataRef.current = new Uint8Array(an.fftSize)
  }

  async function togglePlay() {
    if (!audioRef.current) return
    if (playing) {
      audioRef.current.pause()
      return
    }
    ensureGraph()
    try { await ctxRef.current?.resume() } catch {}
    try {
      await audioRef.current.play()
    } catch (e) {
      console.warn('audio play blocked', e)
    }
  }

  return (
    <section
      id={`module-${module.number}`}
      className={`rounded-2xl shadow-sm border-2 overflow-hidden transition-colors ${
        done ? 'border-emerald-300 bg-emerald-50/30' : 'border-zinc-200 bg-white'
      }`}
    >
      <div className="grid grid-cols-1 md:grid-cols-5 gap-0">
        {/* Consistent Jacky panel — same portrait every module, big module
            emoji + number as the visual hook. Animates when audio plays. */}
        <div className="md:col-span-2 relative min-h-[200px] md:min-h-[280px] bg-gradient-to-br from-zinc-900 via-zinc-800 to-[#A0151B] flex items-center justify-center p-6 overflow-hidden">
          <div className="absolute inset-0 opacity-20" style={{
            backgroundImage: 'radial-gradient(circle at 30% 20%, #FFC107 0%, transparent 35%), radial-gradient(circle at 70% 80%, #D72027 0%, transparent 40%)',
          }} />
          <div className="relative flex flex-col items-center gap-3">
            <JackyVideoAvatar size={140} level={level} idle />
            <div className="text-7xl drop-shadow-lg" aria-hidden>{module.emoji}</div>
          </div>
          <div className="absolute top-3 left-3 bg-white/95 backdrop-blur-sm px-3 py-1.5 rounded-full text-xs font-extrabold text-zinc-700 shadow">
            Module {module.number} of 11
          </div>
        </div>

        {/* Content */}
        <div className="md:col-span-3 p-5 sm:p-6 flex flex-col">
          <div className="flex items-start justify-between gap-3 mb-2">
            <div>
              <h3 className="text-xl font-extrabold text-zinc-900 leading-tight">{module.title}</h3>
              <p className="text-sm text-zinc-600 mt-0.5">{module.subtitle}</p>
            </div>
            <button
              onClick={onToggleDone}
              className={`shrink-0 w-7 h-7 rounded-full border-2 flex items-center justify-center text-sm font-extrabold ${
                done ? 'bg-emerald-500 border-emerald-600 text-white' : 'border-zinc-300 hover:border-emerald-500'
              }`}
              aria-label={done ? 'Mark not done' : 'Mark done'}
            >
              {done && '✓'}
            </button>
          </div>

          <ul className="mt-3 space-y-1.5 text-sm">
            {module.bullets.map((b, i) => (
              <li key={i} className="flex items-baseline gap-2 text-zinc-700">
                <span className="text-amber-500 shrink-0">★</span>
                <span>{b}</span>
              </li>
            ))}
          </ul>

          <details className="mt-4 group">
            <summary className="cursor-pointer text-xs font-extrabold uppercase tracking-wider text-zinc-500 hover:text-zinc-900">
              ▸ Read the full walkthrough
            </summary>
            <p className="mt-3 text-sm text-zinc-700 leading-relaxed whitespace-pre-wrap">{module.script}</p>
          </details>

          <div className="mt-auto pt-5 flex items-center gap-2 flex-wrap">
            <button
              onClick={togglePlay}
              className={`text-sm font-extrabold px-4 py-2 rounded-xl border-2 transition-colors ${
                playing
                  ? 'bg-red-500 border-red-600 text-white'
                  : 'bg-white border-zinc-300 text-zinc-700 hover:border-[#D72027] hover:text-[#D72027]'
              }`}
            >
              {playing ? '⏸ Pause Jacky' : '▶ Play Jacky video'}
            </button>
            {module.tryItPath && (
              <a
                href={module.tryItPath}
                className="text-sm font-extrabold px-4 py-2 rounded-xl bg-gradient-to-r from-[#D72027] to-[#A0151B] text-white shadow-md hover:shadow-lg"
              >
                Try it now →
              </a>
            )}
            {/* The actual audio element — invisible but ref'd. preload=none so
                you only pay the bandwidth when someone hits play. */}
            <audio
              ref={audioRef}
              src={`/training/audio/${module.id}.mp3`}
              preload="none"
              onPlay={() => {
                setPlaying(true)
                onSpeakStateChange(true)
                if (rafRef.current == null) rafRef.current = requestAnimationFrame(tickAnalyser)
              }}
              onPause={() => {
                setPlaying(false)
                onSpeakStateChange(false)
                if (rafRef.current != null) { cancelAnimationFrame(rafRef.current); rafRef.current = null }
                setLevel(0)
              }}
              onEnded={() => {
                setPlaying(false)
                onSpeakStateChange(false)
                if (rafRef.current != null) { cancelAnimationFrame(rafRef.current); rafRef.current = null }
                setLevel(0)
              }}
            />
          </div>
        </div>
      </div>
    </section>
  )
}

// ────────────────────────────────────────────────────────────────────
// Submit Ticket modal — fires an internal note + email to admin@
// ────────────────────────────────────────────────────────────────────

function TicketModal({ onClose, userName }: { onClose: () => void; userName: string | null }) {
  const [subject, setSubject] = useState('')
  const [body, setBody] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function submit() {
    if (!subject.trim() || !body.trim()) { setError('Both fields required.'); return }
    setSubmitting(true)
    setError(null)
    const res = await submitSupportTicket({ subject: subject.trim(), body: body.trim() })
    setSubmitting(false)
    if (!res.ok) { setError(res.error); return }
    setSubmitted(true)
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-3xl shadow-2xl max-w-lg w-full p-6" onClick={(e) => e.stopPropagation()}>
        {submitted ? (
          <div className="text-center py-6">
            <div className="text-5xl mb-3">✅</div>
            <h3 className="text-xl font-extrabold text-zinc-900 mb-2">Ticket submitted</h3>
            <p className="text-sm text-zinc-600 mb-5">Thanks{userName ? `, ${userName}` : ''}. Rhett will get back to you soon.</p>
            <button onClick={onClose} className="bg-zinc-900 text-white font-extrabold text-sm px-5 py-2.5 rounded-xl">Close</button>
          </div>
        ) : (
          <>
            <div className="flex items-start gap-3 mb-4">
              <span className="text-3xl">🎫</span>
              <div>
                <h3 className="text-xl font-extrabold text-zinc-900">Submit a support ticket</h3>
                <p className="text-xs text-zinc-500">Goes straight to admin@bigstarcircus.com.au and an internal note is logged.</p>
              </div>
            </div>
            <div className="space-y-3">
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Subject (one-liner)"
                className="w-full px-3 py-2 border-2 border-zinc-200 rounded-xl text-sm font-bold focus:border-[#D72027] focus:outline-none"
              />
              <textarea
                value={body}
                onChange={(e) => setBody(e.target.value)}
                rows={6}
                placeholder="What's going on? Steps to reproduce, what you expected, what happened."
                className="w-full px-3 py-2 border-2 border-zinc-200 rounded-xl text-sm focus:border-[#D72027] focus:outline-none"
              />
              {error && <div className="text-xs text-red-700 bg-red-50 border-l-2 border-red-400 px-2 py-1 rounded">{error}</div>}
              <div className="flex justify-end gap-2">
                <button onClick={onClose} className="text-sm font-bold text-zinc-600 px-3 py-2 rounded-lg hover:bg-zinc-100">Cancel</button>
                <button
                  onClick={submit}
                  disabled={submitting || !subject.trim() || !body.trim()}
                  className="bg-gradient-to-r from-[#D72027] to-[#A0151B] text-white font-extrabold text-sm px-5 py-2.5 rounded-xl disabled:opacity-50"
                >
                  {submitting ? 'Submitting…' : '🎫 Submit ticket'}
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
