// AUTO-GENERATED by scripts/generate-media-stats.mjs.
export const mediaStats = {
  "generatedAt": "2026-05-13T01:06:59.262Z",
  "totalItems": 2073,
  "totalImages": 1803,
  "totalVideos": 270,
  "totalHeic": 1038,
  "totalBytes": 18969141015,
  "totalGB": 17.67,
  "byYear": {
    "2015": 1,
    "2016": 1,
    "2018": 1,
    "2020": 1,
    "2023": 3,
    "2024": 777,
    "2025": 894,
    "2026": 395
  },
  "topFolders": [
    {
      "name": "BSC / BigStar",
      "count": 317
    },
    {
      "name": "BigStar Workshop Pic / Dec 2024 SHW",
      "count": 231
    },
    {
      "name": "Pictures / Screenshots",
      "count": 158
    },
    {
      "name": "BigStar / Bigstar Circus Tues 9.12.25",
      "count": 97
    },
    {
      "name": "Pictures / Instagram itally highlights",
      "count": 97
    },
    {
      "name": "Skill Card Aerial Pic / random",
      "count": 92
    },
    {
      "name": "BigStar Workshop Pic / April SHW 2026",
      "count": 84
    },
    {
      "name": "MARKETING / Marketing Images",
      "count": 79
    },
    {
      "name": "BigStar Workshop Pic / low res",
      "count": 78
    },
    {
      "name": "BigStar Workshop Pic / OSHS WOrkshop",
      "count": 65
    },
    {
      "name": "Birthday Party Images / BSC birthday party",
      "count": 63
    },
    {
      "name": "easter school holidays 2025 / 7th april",
      "count": 63
    }
  ],
  "dupSets": 101,
  "dupExtras": 107,
  "dupBytes": 427337320,
  "dupGB": 0.4,
  "recentExamples": [
    {
      "name": "Screenshot 2026-05-12 220140.png",
      "ext": "png",
      "sizeKB": 6,
      "mtime": "2026-05-12T12:01:41.128Z",
      "sha8": "6cdac4e8"
    },
    {
      "name": "Screenshot 2026-05-12 213955.png",
      "ext": "png",
      "sizeKB": 323,
      "mtime": "2026-05-12T11:39:56.105Z",
      "sha8": "0ebc9656"
    },
    {
      "name": "Screenshot 2026-05-12 213845.png",
      "ext": "png",
      "sizeKB": 281,
      "mtime": "2026-05-12T11:38:45.818Z",
      "sha8": "0869bddf"
    },
    {
      "name": "Screenshot 2026-05-12 213732.png",
      "ext": "png",
      "sizeKB": 347,
      "mtime": "2026-05-12T11:37:32.831Z",
      "sha8": "63ea622c"
    },
    {
      "name": "Screenshot 2026-05-12 211822.png",
      "ext": "png",
      "sizeKB": 208,
      "mtime": "2026-05-12T11:18:22.336Z",
      "sha8": "6626b76c"
    },
    {
      "name": "Screenshot 2026-05-12 210030.png",
      "ext": "png",
      "sizeKB": 287,
      "mtime": "2026-05-12T11:00:30.699Z",
      "sha8": "0305bc26"
    },
    {
      "name": "Screenshot 2026-05-12 205749.png",
      "ext": "png",
      "sizeKB": 177,
      "mtime": "2026-05-12T10:57:49.446Z",
      "sha8": "c86156b2"
    },
    {
      "name": "Screenshot 2026-05-12 205153.png",
      "ext": "png",
      "sizeKB": 152,
      "mtime": "2026-05-12T10:51:53.497Z",
      "sha8": "424ba092"
    }
  ]
} as const
export const duplicateGroups = [
  {
    "sha8": "15ebd61d",
    "count": 2,
    "size": 1301068,
    "files": [
      "011-Z92_9144.jpg",
      "011-Z92_9144.jpg"
    ]
  },
  {
    "sha8": "34718bc8",
    "count": 2,
    "size": 1500840,
    "files": [
      "035-Z92_9316.jpg",
      "035-Z92_9316.jpg"
    ]
  },
  {
    "sha8": "4869b717",
    "count": 2,
    "size": 1242953,
    "files": [
      "20250120_144717.heic",
      "20250120_144717.heic"
    ]
  },
  {
    "sha8": "62eefbe8",
    "count": 2,
    "size": 2188393,
    "files": [
      "20250120_145201.heic",
      "20250120_145201.heic"
    ]
  },
  {
    "sha8": "87a0f70c",
    "count": 3,
    "size": 3066452,
    "files": [
      "flowersticks.jpg",
      "flowersticks.jpg",
      "flowersticks.jpg"
    ]
  },
  {
    "sha8": "13851d39",
    "count": 3,
    "size": 2420579,
    "files": [
      "plate spining.jpg",
      "plate spining.jpg",
      "plate spining.jpg"
    ]
  },
  {
    "sha8": "f7db5cb5",
    "count": 2,
    "size": 46115,
    "files": [
      "Screenshot 2025-03-16 063425.png",
      "Screenshot 2025-03-16 063425.png"
    ]
  },
  {
    "sha8": "3ecbf44a",
    "count": 2,
    "size": 15006,
    "files": [
      "Screenshot 2025-03-16 064922.png",
      "Screenshot 2025-03-16 064922.png"
    ]
  },
  {
    "sha8": "f354aa04",
    "count": 2,
    "size": 123903,
    "files": [
      "FB_IMG_1749411536188.jpg",
      "FB_IMG_1749411536188.jpg"
    ]
  },
  {
    "sha8": "a315eefa",
    "count": 2,
    "size": 157161,
    "files": [
      "FB_IMG_1749411516545.jpg",
      "1000018180.jpg"
    ]
  },
  {
    "sha8": "fe8be338",
    "count": 2,
    "size": 230098,
    "files": [
      "FB_IMG_1749411507717.jpg",
      "1000018179.jpg"
    ]
  },
  {
    "sha8": "1304ba63",
    "count": 2,
    "size": 149683,
    "files": [
      "FB_IMG_1749411495939.jpg",
      "1000018178.jpg"
    ]
  },
  {
    "sha8": "f8c47497",
    "count": 2,
    "size": 1682280,
    "files": [
      "BigStar Group Shot.jpg",
      "077-Z92_9599.jpg"
    ]
  },
  {
    "sha8": "f6a12ef5",
    "count": 3,
    "size": 2204330,
    "files": [
      "Birthday Party Image 1.jpg",
      "1.jpg",
      "1.jpg"
    ]
  },
  {
    "sha8": "c3907fe2",
    "count": 3,
    "size": 1579062,
    "files": [
      "BP 2.jpg",
      "3.jpg",
      "3.jpg"
    ]
  },
  {
    "sha8": "9f6565c6",
    "count": 3,
    "size": 2176203,
    "files": [
      "BP 3.jpg",
      "20241103_122534.jpg",
      "20241103_122534.jpg"
    ]
  },
  {
    "sha8": "6cfc473e",
    "count": 3,
    "size": 2390523,
    "files": [
      "BP 4.jpg",
      "2.jpg",
      "2.jpg"
    ]
  },
  {
    "sha8": "c11975f5",
    "count": 2,
    "size": 34384633,
    "files": [
      "20241103_105339.mp4",
      "20241103_105339.mp4"
    ]
  },
  {
    "sha8": "6140048f",
    "count": 2,
    "size": 33592137,
    "files": [
      "20241103_105445.mp4",
      "20241103_105445.mp4"
    ]
  },
  {
    "sha8": "92a09f33",
    "count": 2,
    "size": 7851560,
    "files": [
      "20241103_111900.mp4",
      "20241103_111900.mp4"
    ]
  },
  {
    "sha8": "ee27e493",
    "count": 2,
    "size": 1921944,
    "files": [
      "20241103_115253.heic",
      "20241103_115253.heic"
    ]
  },
  {
    "sha8": "827cdcc6",
    "count": 2,
    "size": 1932758,
    "files": [
      "20241103_115254.heic",
      "20241103_115254.heic"
    ]
  },
  {
    "sha8": "e0f5c97d",
    "count": 2,
    "size": 1813959,
    "files": [
      "20241103_115259(0).heic",
      "20241103_115259(0).heic"
    ]
  },
  {
    "sha8": "3205dd42",
    "count": 2,
    "size": 1848974,
    "files": [
      "20241103_115259.heic",
      "20241103_115259.heic"
    ]
  },
  {
    "sha8": "d88ba90c",
    "count": 2,
    "size": 1883541,
    "files": [
      "20241103_115300.heic",
      "20241103_115300.heic"
    ]
  },
  {
    "sha8": "c6ee04f8",
    "count": 2,
    "size": 35542312,
    "files": [
      "20241103_120837.mp4",
      "20241103_120837.mp4"
    ]
  },
  {
    "sha8": "f72db9ad",
    "count": 2,
    "size": 1988988,
    "files": [
      "20241103_122511.heic",
      "20241103_122511.heic"
    ]
  },
  {
    "sha8": "e2a84241",
    "count": 2,
    "size": 2200218,
    "files": [
      "20241103_122517.heic",
      "20241103_122517.heic"
    ]
  },
  {
    "sha8": "345c795e",
    "count": 2,
    "size": 1425775,
    "files": [
      "20241103_122520.heic",
      "20241103_122520.heic"
    ]
  },
  {
    "sha8": "5eada9fb",
    "count": 2,
    "size": 2397031,
    "files": [
      "20241103_122523(0).heic",
      "20241103_122523(0).heic"
    ]
  },
  {
    "sha8": "ad654c32",
    "count": 2,
    "size": 2597191,
    "files": [
      "20241103_122523.heic",
      "20241103_122523.heic"
    ]
  },
  {
    "sha8": "e824de4b",
    "count": 2,
    "size": 1963830,
    "files": [
      "20241103_122524.heic",
      "20241103_122524.heic"
    ]
  },
  {
    "sha8": "054f00f1",
    "count": 2,
    "size": 1614691,
    "files": [
      "20241103_122525.heic",
      "20241103_122525.heic"
    ]
  },
  {
    "sha8": "8e52ea74",
    "count": 2,
    "size": 1951928,
    "files": [
      "20241103_122533(0).heic",
      "20241103_122533(0).heic"
    ]
  },
  {
    "sha8": "04fc06ee",
    "count": 2,
    "size": 1794244,
    "files": [
      "20241103_122533.heic",
      "20241103_122533.heic"
    ]
  },
  {
    "sha8": "689f27cf",
    "count": 2,
    "size": 1679349,
    "files": [
      "20241103_122534.heic",
      "20241103_122534.heic"
    ]
  },
  {
    "sha8": "3a0991fe",
    "count": 2,
    "size": 1733452,
    "files": [
      "20241103_122537.heic",
      "20241103_122537.heic"
    ]
  },
  {
    "sha8": "da821372",
    "count": 2,
    "size": 2371231,
    "files": [
      "20241103_122543.heic",
      "20241103_122543.heic"
    ]
  },
  {
    "sha8": "81786fa0",
    "count": 2,
    "size": 2321044,
    "files": [
      "20241103_122544.heic",
      "20241103_122544.heic"
    ]
  },
  {
    "sha8": "01230a73",
    "count": 2,
    "size": 2362323,
    "files": [
      "20241103_122545.heic",
      "20241103_122545.heic"
    ]
  },
  {
    "sha8": "40f87e50",
    "count": 2,
    "size": 2522690,
    "files": [
      "20241103_122546.heic",
      "20241103_122546.heic"
    ]
  },
  {
    "sha8": "f68ea37f",
    "count": 2,
    "size": 2077511,
    "files": [
      "20241103_123527.heic",
      "20241103_123527.heic"
    ]
  },
  {
    "sha8": "d4207584",
    "count": 2,
    "size": 1962509,
    "files": [
      "20241103_123529.heic",
      "20241103_123529.heic"
    ]
  },
  {
    "sha8": "0e796c83",
    "count": 2,
    "size": 1846904,
    "files": [
      "20241103_123530.heic",
      "20241103_123530.heic"
    ]
  },
  {
    "sha8": "a9b1731d",
    "count": 2,
    "size": 2206001,
    "files": [
      "20241103_123536.heic",
      "20241103_123536.heic"
    ]
  },
  {
    "sha8": "e206161b",
    "count": 2,
    "size": 2126350,
    "files": [
      "20241103_123537.heic",
      "20241103_123537.heic"
    ]
  },
  {
    "sha8": "1e7fb1f3",
    "count": 2,
    "size": 2265246,
    "files": [
      "20241103_123541.heic",
      "20241103_123541.heic"
    ]
  },
  {
    "sha8": "1dac0f49",
    "count": 2,
    "size": 1586442,
    "files": [
      "20241103_124528.heic",
      "20241103_124528.heic"
    ]
  },
  {
    "sha8": "e096603b",
    "count": 2,
    "size": 1749536,
    "files": [
      "20241103_124530.heic",
      "20241103_124530.heic"
    ]
  },
  {
    "sha8": "c21a51c2",
    "count": 2,
    "size": 1770414,
    "files": [
      "20241103_124531(0).heic",
      "20241103_124531(0).heic"
    ]
  },
  {
    "sha8": "279c07b9",
    "count": 2,
    "size": 2391251,
    "files": [
      "20241103_124531.heic",
      "20241103_124531.heic"
    ]
  },
  {
    "sha8": "a6969e5e",
    "count": 2,
    "size": 2081388,
    "files": [
      "20241103_124538.heic",
      "20241103_124538.heic"
    ]
  },
  {
    "sha8": "9461df0d",
    "count": 2,
    "size": 1588683,
    "files": [
      "20241103_124539(0).heic",
      "20241103_124539(0).heic"
    ]
  },
  {
    "sha8": "fe22e597",
    "count": 2,
    "size": 1684325,
    "files": [
      "20241103_124539.heic",
      "20241103_124539.heic"
    ]
  },
  {
    "sha8": "29c0d922",
    "count": 2,
    "size": 1487849,
    "files": [
      "20241103_124540(0).heic",
      "20241103_124540(0).heic"
    ]
  },
  {
    "sha8": "5b8ef2e2",
    "count": 2,
    "size": 1481914,
    "files": [
      "20241103_124540.heic",
      "20241103_124540.heic"
    ]
  },
  {
    "sha8": "5e12574a",
    "count": 2,
    "size": 1386058,
    "files": [
      "20241103_124541.heic",
      "20241103_124541.heic"
    ]
  },
  {
    "sha8": "5c1c2494",
    "count": 2,
    "size": 1994812,
    "files": [
      "20241103_124543.heic",
      "20241103_124543.heic"
    ]
  },
  {
    "sha8": "fc398469",
    "count": 2,
    "size": 1744439,
    "files": [
      "20241103_124545.heic",
      "20241103_124545.heic"
    ]
  },
  {
    "sha8": "3c4ef7e1",
    "count": 2,
    "size": 2512921,
    "files": [
      "20241103_124547(0).heic",
      "20241103_124547(0).heic"
    ]
  },
  {
    "sha8": "12165a89",
    "count": 2,
    "size": 1610074,
    "files": [
      "20241103_124547.heic",
      "20241103_124547.heic"
    ]
  },
  {
    "sha8": "b1147a58",
    "count": 2,
    "size": 2162970,
    "files": [
      "20241103_124551.heic",
      "20241103_124551.heic"
    ]
  },
  {
    "sha8": "f065ae69",
    "count": 2,
    "size": 2070367,
    "files": [
      "20241103_124552.heic",
      "20241103_124552.heic"
    ]
  },
  {
    "sha8": "0e5252b0",
    "count": 2,
    "size": 1511321,
    "files": [
      "20241103_124903.heic",
      "20241103_124903.heic"
    ]
  },
  {
    "sha8": "13107c19",
    "count": 2,
    "size": 2372899,
    "files": [
      "20241103_124904(0).heic",
      "20241103_124904(0).heic"
    ]
  },
  {
    "sha8": "78c1d898",
    "count": 2,
    "size": 1502266,
    "files": [
      "20241103_124904.heic",
      "20241103_124904.heic"
    ]
  },
  {
    "sha8": "62f33205",
    "count": 2,
    "size": 1695364,
    "files": [
      "20241103_124906.heic",
      "20241103_124906.heic"
    ]
  },
  {
    "sha8": "32666324",
    "count": 2,
    "size": 6078717,
    "files": [
      "20241103_125643.jpg",
      "20241103_125643.jpg"
    ]
  },
  {
    "sha8": "6a3c751e",
    "count": 2,
    "size": 4829676,
    "files": [
      "20241103_125654.jpg",
      "20241103_125654.jpg"
    ]
  },
  {
    "sha8": "5e262526",
    "count": 2,
    "size": 5339558,
    "files": [
      "20241103_125725.mp4",
      "20241103_125725.mp4"
    ]
  },
  {
    "sha8": "b05451dd",
    "count": 2,
    "size": 3109852,
    "files": [
      "20241103_125821.heic",
      "20241103_125821.heic"
    ]
  },
  {
    "sha8": "39c0f859",
    "count": 2,
    "size": 3098020,
    "files": [
      "20241103_125822.heic",
      "20241103_125822.heic"
    ]
  },
  {
    "sha8": "f900fefe",
    "count": 2,
    "size": 7449318,
    "files": [
      "20241103_125824.jpg",
      "20241103_125824.jpg"
    ]
  },
  {
    "sha8": "3c8b40a1",
    "count": 2,
    "size": 3651837,
    "files": [
      "20241103_125825.jpg",
      "20241103_125825.jpg"
    ]
  },
  {
    "sha8": "028d09f1",
    "count": 2,
    "size": 3721489,
    "files": [
      "20241103_125826.jpg",
      "20241103_125826.jpg"
    ]
  },
  {
    "sha8": "491ca384",
    "count": 2,
    "size": 1794381,
    "files": [
      "20241103_125843.heic",
      "20241103_125843.heic"
    ]
  },
  {
    "sha8": "f602b778",
    "count": 2,
    "size": 1858211,
    "files": [
      "20241103_130117.heic",
      "20241103_130117.heic"
    ]
  },
  {
    "sha8": "7208475f",
    "count": 2,
    "size": 2249211,
    "files": [
      "20241103_130137(0).heic",
      "20241103_130137(0).heic"
    ]
  },
  {
    "sha8": "f691c33a",
    "count": 2,
    "size": 2288874,
    "files": [
      "20241103_130137(1).heic",
      "20241103_130137(1).heic"
    ]
  },
  {
    "sha8": "0c7d7b26",
    "count": 2,
    "size": 2142820,
    "files": [
      "20241103_130137.heic",
      "20241103_130137.heic"
    ]
  },
  {
    "sha8": "0ce1eccf",
    "count": 2,
    "size": 2102136,
    "files": [
      "4.jpg",
      "4.jpg"
    ]
  },
  {
    "sha8": "5c65fac6",
    "count": 2,
    "size": 633364,
    "files": [
      "Bigstar transparent logo JPG.jpg",
      "Bigstar transparent logo JPG.jpg"
    ]
  },
  {
    "sha8": "6f32c018",
    "count": 2,
    "size": 325704,
    "files": [
      "IMG-20240520-WA0040.jpg",
      "WhatsApp Image 2024-05-20 at 14.57.03_7152d8aa.jpg"
    ]
  },
  {
    "sha8": "517059d1",
    "count": 2,
    "size": 363473,
    "files": [
      "IMG-20240520-WA0041.jpg",
      "WhatsApp Image 2024-05-20 at 14.57.06_2ac03939.jpg"
    ]
  },
  {
    "sha8": "8e3f634e",
    "count": 2,
    "size": 380219,
    "files": [
      "IMG-20240520-WA0042.jpg",
      "WhatsApp Image 2024-05-20 at 14.57.06_ca191da8.jpg"
    ]
  },
  {
    "sha8": "ede07d3b",
    "count": 2,
    "size": 337038,
    "files": [
      "IMG-20240520-WA0044.jpg",
      "WhatsApp Image 2024-05-20 at 14.57.06_f9fc9be2.jpg"
    ]
  },
  {
    "sha8": "f1600dc8",
    "count": 2,
    "size": 26015423,
    "files": [
      "VID-20241201-WA0003.mp4",
      "VID-20241201-WA0003.mp4"
    ]
  },
  {
    "sha8": "801b636e",
    "count": 2,
    "size": 38655930,
    "files": [
      "VID-20241201-WA0004.mp4",
      "VID-20241201-WA0004.mp4"
    ]
  },
  {
    "sha8": "56a74199",
    "count": 2,
    "size": 26093248,
    "files": [
      "VID-20241201-WA0005.mp4",
      "VID-20241201-WA0005.mp4"
    ]
  },
  {
    "sha8": "64afb126",
    "count": 2,
    "size": 2335858,
    "files": [
      "VID-20241203-WA0000.mp4",
      "VID-20241203-WA0000.mp4"
    ]
  },
  {
    "sha8": "b4ed4f26",
    "count": 2,
    "size": 24163619,
    "files": [
      "VID-20241212-WA0000.mp4",
      "VID-20241212-WA0000.mp4"
    ]
  },
  {
    "sha8": "0e83e5d3",
    "count": 2,
    "size": 1590918,
    "files": [
      "004-Z92_9106.jpg",
      "004-Z92_9106.jpg"
    ]
  },
  {
    "sha8": "5dfc3c8d",
    "count": 2,
    "size": 1604618,
    "files": [
      "006-Z92_9124.jpg",
      "006-Z92_9124.jpg"
    ]
  },
  {
    "sha8": "faec2ddb",
    "count": 2,
    "size": 1290714,
    "files": [
      "010-Z92_9141.jpg",
      "010-Z92_9141.jpg"
    ]
  },
  {
    "sha8": "279422f7",
    "count": 2,
    "size": 1425476,
    "files": [
      "015-Z92_9177.jpg",
      "015-Z92_9177.jpg"
    ]
  },
  {
    "sha8": "a737bdbe",
    "count": 2,
    "size": 1771547,
    "files": [
      "032-Z92_9305.jpg",
      "032-Z92_9305.jpg"
    ]
  },
  {
    "sha8": "c3486fa4",
    "count": 2,
    "size": 2722946,
    "files": [
      "circus.jpg",
      "circus.jpg"
    ]
  },
  {
    "sha8": "49239e9a",
    "count": 2,
    "size": 2726401,
    "files": [
      "hoops.jpg",
      "hoops.jpg"
    ]
  },
  {
    "sha8": "aa421d4d",
    "count": 2,
    "size": 3065434,
    "files": [
      "jump.jpg",
      "jump.jpg"
    ]
  },
  {
    "sha8": "037bcabb",
    "count": 2,
    "size": 2555398,
    "files": [
      "stretching.jpg",
      "stretching.jpg"
    ]
  }
] as const
export type MediaStats = typeof mediaStats
