// AUTO-GENERATED by scripts/generate-media-stats.mjs — do not edit by hand.
// Source: media-catalog.json (kept locally; this file is the privacy-safe
// summary that's safe to deploy.)

export const mediaStats = {
  "generatedAt": "2026-05-13T01:06:59.262Z",
  "totalItems": 2073,
  "totalImages": 1803,
  "totalVideos": 270,
  "totalHeic": 1038,
  "totalBytes": 18969141015,
  "totalGB": 17.67,
  "byYear": {
    "2015": 1,
    "2016": 1,
    "2018": 1,
    "2020": 1,
    "2023": 3,
    "2024": 777,
    "2025": 894,
    "2026": 395
  },
  "topFolders": [
    {
      "name": "BSC / BigStar",
      "count": 317
    },
    {
      "name": "BigStar Workshop Pic / Dec 2024 SHW",
      "count": 231
    },
    {
      "name": "Pictures / Screenshots",
      "count": 158
    },
    {
      "name": "BigStar / Bigstar Circus Tues 9.12.25",
      "count": 97
    },
    {
      "name": "Pictures / Instagram itally highlights",
      "count": 97
    },
    {
      "name": "Skill Card Aerial Pic / random",
      "count": 92
    },
    {
      "name": "BigStar Workshop Pic / April SHW 2026",
      "count": 84
    },
    {
      "name": "MARKETING / Marketing Images",
      "count": 79
    },
    {
      "name": "BigStar Workshop Pic / low res",
      "count": 78
    },
    {
      "name": "BigStar Workshop Pic / OSHS WOrkshop",
      "count": 65
    },
    {
      "name": "Birthday Party Images / BSC birthday party",
      "count": 63
    },
    {
      "name": "easter school holidays 2025 / 7th april",
      "count": 63
    }
  ],
  "dupSets": 101,
  "dupExtras": 107,
  "dupBytes": 427337320,
  "dupGB": 0.4,
  "recentExamples": [
    {
      "name": "Screenshot 2026-05-12 220140.png",
      "ext": "png",
      "sizeKB": 6,
      "mtime": "2026-05-12T12:01:41.128Z",
      "sha8": "6cdac4e8"
    },
    {
      "name": "Screenshot 2026-05-12 213955.png",
      "ext": "png",
      "sizeKB": 323,
      "mtime": "2026-05-12T11:39:56.105Z",
      "sha8": "0ebc9656"
    },
    {
      "name": "Screenshot 2026-05-12 213845.png",
      "ext": "png",
      "sizeKB": 281,
      "mtime": "2026-05-12T11:38:45.818Z",
      "sha8": "0869bddf"
    },
    {
      "name": "Screenshot 2026-05-12 213732.png",
      "ext": "png",
      "sizeKB": 347,
      "mtime": "2026-05-12T11:37:32.831Z",
      "sha8": "63ea622c"
    },
    {
      "name": "Screenshot 2026-05-12 211822.png",
      "ext": "png",
      "sizeKB": 208,
      "mtime": "2026-05-12T11:18:22.336Z",
      "sha8": "6626b76c"
    },
    {
      "name": "Screenshot 2026-05-12 210030.png",
      "ext": "png",
      "sizeKB": 287,
      "mtime": "2026-05-12T11:00:30.699Z",
      "sha8": "0305bc26"
    },
    {
      "name": "Screenshot 2026-05-12 205749.png",
      "ext": "png",
      "sizeKB": 177,
      "mtime": "2026-05-12T10:57:49.446Z",
      "sha8": "c86156b2"
    },
    {
      "name": "Screenshot 2026-05-12 205153.png",
      "ext": "png",
      "sizeKB": 152,
      "mtime": "2026-05-12T10:51:53.497Z",
      "sha8": "424ba092"
    }
  ]
} as const

export type MediaStats = typeof mediaStats
